-- Run in SQL Editor / CLI against a development project. Entire test transaction rolls back.
begin;
create function pg_temp.check(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;end$$;
do $$
declare buyer uuid:=gen_random_uuid();buyer2 uuid:=gen_random_uuid();dealer uuid:=gen_random_uuid();dealer2 uuid:=gen_random_uuid();admin uuid:=gen_random_uuid();sid uuid:=gen_random_uuid();x uuid;claims jsonb;r jsonb;p jsonb;off jsonb;lead jsonb;lid text;code text;updated float8;did bigint;
begin
 perform pg_temp.check(jsonb_array_length(public.volteo_api('/vehicles'))>0,'public catalog');
 perform pg_temp.check(public.volteo_api('/me')->>'status'='401','anonymous denied');
 foreach x in array array[buyer,buyer2,dealer,dealer2,admin] loop
  insert into auth.users(id,email,raw_user_meta_data) values(x,x||'@volteo-test.invalid','{"name":"Test","role":"admin","dealer_id":1}');
  insert into auth.sessions(id,user_id,created_at,updated_at,aal) values(x,x,now(),now(),'aal1');
 end loop;
 perform pg_temp.check((select role='user' and dealer_id is null from volteo_private.users where id=buyer),'metadata cannot elevate role');
 update volteo_private.users set role='admin' where id=admin;
 update volteo_private.users set role='dealer',account_type='pro',dealer_id=1 where id in(dealer,dealer2);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',admin,'session_id',admin,'role','authenticated')::text,true);
 r=public.volteo_api('/pilot/partners','PUT','{"name":"Test concession","city":"Les Ulis","address":"1 rue de test","evidence":"Test transactionnel, pas un partenaire réel","lat":48.6817,"lon":2.1864,"status":"verified","verification_ack":true,"brands":["Peugeot"]}');
 perform pg_temp.check(not(r ? 'error'),'partner creation: '||r::text);did=(r->>'dealer_id')::bigint;
 update volteo_private.users set dealer_id=did where id=dealer;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',dealer,'session_id',dealer,'role','authenticated')::text,true);
 off=public.volteo_api('/pilot/inventory','POST','{"vehicle_slug":"peugeot-e-208","trim":"GT test","cash_price":30000,"fees":0,"availability":"Test uniquement","terms":"Offre de test non réelle","source":"Test automatisé","stock_ack":true,"valid_days":7}');
 perform pg_temp.check(not(off ? 'error'),'offer creation: '||off::text);
 r=public.volteo_api('/project','PUT','{}');perform pg_temp.check(r->>'status'='403','pro cannot use buyer project');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',buyer,'session_id',buyer,'role','authenticated')::text,true);
 p='{"budget":40000,"km":25000,"daily":60,"seats":5,"charging":"home","usage":"mixed","category":"Toutes","postcode":"91940","horizon":"3months","payment":"finance","tradeIn":"undecided","parking":"private","chargingReady":"confirmed","chargeRate":0.29}';
 r=public.volteo_api('/project','PUT',p);perform pg_temp.check(r->'project'->>'km'='25000','project saved: '||r::text);
 r=public.volteo_api('/me');perform pg_temp.check(r->'profile'->>'km'='25000','profile coherence');
 r=public.volteo_api('/favorites/peugeot-e-208','PUT');perform pg_temp.check(r->>'ok'='true','favorite');
 r=public.volteo_api('/simulations','POST','{"vehicle":"peugeot-e-208"}');perform pg_temp.check(r ? 'id','simulation: '||r::text);
 r=public.volteo_api('/leads','POST',jsonb_build_object('vehicle','peugeot-e-208','dealer_id',did,'phone','0612345678','consent',false));perform pg_temp.check(r ? 'error','consent required');
 r=public.volteo_api('/leads','POST',jsonb_build_object('vehicle','peugeot-e-208','dealer_id',did,'phone','0612345678','consent',true,'share_project',true,'offer_id',off->>'id','trial','{"priorities":["Recharge"]}'::jsonb));
 perform pg_temp.check(r ? 'id','lead: '||r::text);lid=r->>'id';
 r=public.volteo_api('/leads');perform pg_temp.check(r->0->'project'->>'km'='25000','snapshot');
 perform pg_temp.check(not(r->0 ? 'attendance_code'),'code unavailable outside appointment');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',buyer2,'session_id',buyer2,'role','authenticated')::text,true);
 perform pg_temp.check(jsonb_array_length(public.volteo_api('/leads'))=0,'buyer isolation');
 perform pg_temp.check(public.volteo_api('/leads/'||lid,'DELETE')->>'status'='403','other buyer cannot delete');
 perform pg_temp.check(public.volteo_api('/admin/users')->>'status'='403','buyer cannot list accounts');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',dealer2,'session_id',dealer2,'role','authenticated')::text,true);
 perform pg_temp.check(jsonb_array_length(public.volteo_api('/leads'))=0,'dealer isolation');
 r=public.volteo_api('/pilot/inventory/'||(off->>'id'),'PUT',off||jsonb_build_object('expected_updated',off->'updated'));perform pg_temp.check(r->>'status'='403','other dealer cannot edit offer: '||r::text);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',dealer,'session_id',dealer,'role','authenticated')::text,true);
 lead=public.volteo_api('/leads')->0;perform pg_temp.check(lead->>'id'=lid and not(lead ? 'attendance_code'),'dealer assigned lead without code');
 r=public.volteo_api('/leads/'||lid,'PATCH',jsonb_build_object('status','Essai planifié','appointment',extract(epoch from now())+60,'expected_updated',lead->'updated'));
 perform pg_temp.check(r->>'ok'='true','appointment: '||r::text);
 r=public.volteo_api('/leads/'||lid,'PATCH',jsonb_build_object('status','Contacté','expected_updated',lead->'updated'));perform pg_temp.check(r->>'status'='409','optimistic conflict');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',buyer,'session_id',buyer,'role','authenticated')::text,true);
 code=public.volteo_api('/leads')->0->>'attendance_code';perform pg_temp.check(code ~ '^[0-9]{6}$','buyer sees six numeric digits');
 -- Exercise a leading-zero code deterministically through the public journey.
 update volteo_private.lead_details set attendance_code='000042' where lead_id=lid;
 code=public.volteo_api('/leads')->0->>'attendance_code';
 perform pg_temp.check(code='000042','leading zeros preserved for buyer');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',dealer,'session_id',dealer,'role','authenticated')::text,true);
 r=public.volteo_api('/pilot/leads/'||lid||'/attendance','POST',jsonb_build_object('code',code));perform pg_temp.check(r->>'ok'='true','attendance: '||r::text);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',buyer,'session_id',buyer,'role','authenticated')::text,true);
 r=public.volteo_api('/pilot/leads/'||lid||'/feedback','PUT','{"outcome":"compare","reason":"charging","liked":"Confort","shared":false}');perform pg_temp.check(r->>'shared'='false','private feedback');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',dealer,'session_id',dealer,'role','authenticated')::text,true);
 perform pg_temp.check(public.volteo_api('/leads')->0->'feedback'='{}'::jsonb,'private feedback hidden');
 perform pg_temp.check(public.volteo_api('/pilot/dashboard')->>'feedback'='0','private feedback excluded from metrics');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',buyer,'session_id',buyer,'role','authenticated')::text,true);
 r=public.volteo_api('/pilot/leads/'||lid||'/feedback','PUT','{"outcome":"compare","reason":"charging","shared":true}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',dealer,'session_id',dealer,'role','authenticated')::text,true);
 perform pg_temp.check(public.volteo_api('/leads')->0->'feedback'->>'reason'='charging','shared feedback visible');
 perform pg_temp.check(public.volteo_api('/pilot/dashboard')->>'feedback'='1','shared metrics');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',buyer,'session_id',buyer,'role','authenticated')::text,true);
 r=public.volteo_api('/pilot/leads/'||lid||'/feedback','PUT','{"outcome":"compare","reason":"charging","shared":false}');
 perform pg_temp.check(public.volteo_api('/export')->'user'->>'id'=buyer::text,'export own data');
 delete from auth.sessions where id=buyer;
 perform pg_temp.check(public.volteo_api('/me')->>'status'='401','revoked access token immediately denied');
 delete from auth.users where id=buyer;
 perform pg_temp.check(not exists(select 1 from volteo_private.leads where id=lid),'account deletion cascades');
 perform pg_temp.check(not has_table_privilege('authenticated','volteo_private.users','SELECT'),'no direct private table grant');
 perform pg_temp.check(not has_function_privilege('anon','public.volteo_geo_cache(text,jsonb)','EXECUTE'),'anonymous cannot forge communes');
end$$;
select 'Cloud security and journey assertions passed; transaction rolled back' as result;
rollback;
