import React,{useState} from 'react';
import {publicPages} from './public-content';
import {siteOrigin} from './seo';
import {measurementConfig} from './measurement';
const campaigns=[
 {key:'budget',name:'Budget & économies',path:'/economies-voiture-electrique',intent:'Comparer le coût thermique / électrique',keywords:['"cout voiture electrique vs thermique"','"simulateur budget voiture electrique"','[rentabilite voiture electrique]'],headlines:['Marre des prix à la pompe ?','Comparez votre budget auto','Votre coût, votre usage'],descriptions:['Achat, recharge, entretien : comparez le coût total selon vos trajets avec VOLTÉO.','L’électrique est-il adapté à votre budget ? Testez vos hypothèses avant de choisir.']},
 {key:'recharge',name:'Préparer sa recharge',path:'/recharge-voiture-electrique',intent:'Évaluer la recharge avant l’achat',keywords:['"voiture electrique sans borne"','"recharge voiture electrique maison"','[budget recharge electrique]'],headlines:['Où recharger au quotidien ?','Préparez votre électrique','Votre recharge, votre rythme'],descriptions:['Domicile, travail, bornes : préparez un scénario adapté à votre quotidien.','Estimez vos besoins et comparez les conditions de recharge avant votre achat.']},
 {key:'essai_ulis',name:'Essai · Les Ulis',path:'/essai-electrique-les-ulis',intent:'Préparer une demande d’essai local',keywords:['"essai voiture electrique les ulis"','"voiture electrique essai essonne"','[essai electrique les ulis]'],headlines:['Votre essai près des Ulis','Préparez le bon essai','Découvrez le pilote VOLTÉO'],descriptions:['Définissez vos priorités et consultez les offres locales disponibles autour des Ulis.','Préparez votre demande. Véhicule et créneau à confirmer par le professionnel.']}
];
export default function Acquisition(){const origin=siteOrigin(import.meta.env.VITE_SITE_URL),[selected,setSelected]=useState('budget'),[budget,setBudget]=useState(20),[cpc,setCpc]=useState(1.5),[rate,setRate]=useState(3),[copied,setCopied]=useState('');const c=campaigns.find(c=>c.key===selected);const url=origin?origin+c.path+'?utm_source=google&utm_medium=cpc&utm_campaign='+c.key:'';const clicks=budget/Math.max(.01,cpc),leads=clicks*rate/100;
 async function copy(){try{await navigator.clipboard.writeText(url);setCopied('Lien copié.');}catch{setCopied('Sélectionnez le lien pour le copier.');}}
 return <section className="acquisition"><div className="dashboard-grid"><article className="panel"><div className="eyebrow">SEO TECHNIQUE</div><h2>Des pages prêtes à être découvertes.</h2><ul className="acquisition-checks"><li>Pages éditoriales rendues en HTML au build</li><li>Titres, descriptions, canonical et partage social par page</li><li>Données structurées WebSite, WebPage et fil d’Ariane</li><li>Sitemap des pages publiques et exclusion des espaces privés</li></ul><p className="notice">{origin?`Domaine canonique : ${origin}`:'À configurer : le domaine public VITE_SITE_URL. Sans domaine, la version reste non indexable.'}</p><p>Search Console non connectée : impressions, clics et positions indisponibles.</p>{Object.entries(publicPages).map(([path,p])=><a className="dashboard-row" href={path} key={path}>{p.title} ↗</a>)}</article><article className="panel"><div className="eyebrow">MESURE & CONVERSIONS</div><h2>Une demande réelle compte.</h2><p>La conversion principale est déclenchée après l’enregistrement réussi d’une demande liée à une offre partenaire. Les simples clics et les demandes de démonstration sont exclus de Google Ads.</p><ul><li>GA4 : {measurementConfig.ga?'identifiant configuré':'non configuré'}</li><li>Google Ads : {measurementConfig.ads&&measurementConfig.label?'identifiant et label configurés':'identifiant ou label à renseigner'}</li><li>Consentement distinct pour audience et publicité</li><li>Aucune coordonnée personnelle dans les événements</li></ul><p className="muted">Identifiants configurés ne signifie pas collecte validée. Les résultats publicitaires ne sont pas connectés à ce tableau de bord.</p></article></div>
 <section className="panel"><div className="eyebrow">PRÉPARATION GOOGLE ADS</div><h2>Un message adapté à chaque intention.</h2><div className="dashboard-tabs">{campaigns.map(x=><button key={x.key} className={selected===x.key?'':'secondary'} aria-pressed={selected===x.key} onClick={()=>{setSelected(x.key);setCopied('');}}>{x.name}</button>)}</div><p><b>Intention :</b> {c.intent}</p><div className="dashboard-grid"><div><h3>Mots-clés de départ</h3><ul>{c.keywords.map(x=><li key={x}><code>{x}</code></li>)}</ul><p>Expressions et mots-clés exacts à vérifier avec les termes réellement recherchés.</p><h3>Exclusions initiales</h3><p>emploi, formation, jouet, miniature, location vacances, réparation téléphone</p></div><div className="ad-preview"><small>Aperçu d’annonce · non publiée</small><h3>{c.headlines.join(' · ')}</h3>{c.descriptions.map(d=><p key={d}>{d}</p>)}<small>{origin||'Domaine à configurer'}</small></div></div><label className="field"><span>Lien de campagne</span><input readOnly value={url} placeholder="Renseigner VITE_SITE_URL au déploiement" onFocus={e=>e.target.select()}/></label><button className="secondary" disabled={!url} onClick={copy}>Copier le lien</button><span role="status"> {copied}</span><p className="muted">Aucune campagne créée ni dépense engagée. Vérifiez annonces, ciblage, budget et suivi avant activation.</p></section>
 <section className="panel"><h2>Planifier un test, avec vos hypothèses.</h2><p>Simulation de campagne : ces valeurs ne sont ni des résultats mesurés ni une prévision garantie.</p><div className="dashboard-filters">{[['Budget quotidien (€)',budget,setBudget,.01],['Coût par clic supposé (€)',cpc,setCpc,.01],['Taux de demande supposé (%)',rate,setRate,.1]].map(([label,value,set,step])=><label key={label}>{label}<input type="number" min={0} max={label.includes('%')?100:10000} step={step} value={value} onChange={e=>set(Math.min(label.includes('%')?100:10000,Math.max(0,Number(e.target.value)||0)))}/></label>)}</div><div className="dashboard-kpis">{[['Budget sur 30 jours',(budget*30).toFixed(0)+' €'],['Clics / jour',cpc>0?clicks.toFixed(1):'—'],['Demandes / mois',cpc>0?(leads*30).toFixed(1):'—'],['Coût / demande',rate>0&&cpc>0?(cpc/(rate/100)).toFixed(2)+' €':'—']].map(([k,v])=><div className="dashboard-kpi" key={k}><span>{k}</span><strong>{v}</strong><small>Hypothèse de travail</small></div>)}</div><p>Commencez sur le territoire réellement couvert. Analysez séparément demandes valides, rendez-vous et essais réalisés. Une présence confirmée ou un achat déclaré ne donne pas, à lui seul, un revenu publicitaire attribué.</p></section></section>;
}
