import React,{useEffect,useRef,useState} from 'react';
import {applyConsent,readConsent,measurementEnabled} from './measurement';
import './dashboard.css';
export default function Consent(){const [saved,setSaved]=useState(readConsent),[open,setOpen]=useState(()=>measurementEnabled&&!readConsent()),[analytics,setAnalytics]=useState(saved?.analytics||false),[ads,setAds]=useState(saved?.ads||false),dialog=useRef(null);
 useEffect(()=>{if(saved)applyConsent(saved,false);const show=()=>setOpen(true);window.addEventListener('volteo-open-consent',show);return()=>window.removeEventListener('volteo-open-consent',show);},[]);
 useEffect(()=>{if(open&&!dialog.current.open)dialog.current.showModal();else if(!open&&dialog.current.open)dialog.current.close();},[open]);
 function save(value){const revoked=(saved?.analytics&&!value.analytics)||(saved?.ads&&!value.ads);applyConsent(value);setSaved(value);setAnalytics(value.analytics);setAds(value.ads);setOpen(false);if(revoked)location.reload();}
 return <dialog className="consent-dialog" ref={dialog} aria-labelledby="consent-title" onCancel={()=>{setOpen(false);}} onClose={()=>setOpen(false)}><h2 id="consent-title">Vos choix de confidentialité.</h2><p>Les fonctions essentielles restent disponibles. Vous pouvez autoriser séparément la mesure d’audience et la mesure des demandes issues des annonces Google. Aucun tag de mesure n’est chargé avant votre accord.</p>{!measurementEnabled&&<p>La mesure externe n’est pas configurée sur cette version.</p>}<label className="checkbox"><input type="checkbox" checked={analytics} onChange={e=>setAnalytics(e.target.checked)}/>Mesure d’audience Google Analytics</label><label className="checkbox"><input type="checkbox" checked={ads} onChange={e=>setAds(e.target.checked)}/>Mesure des conversions Google Ads</label><p>Pas de personnalisation publicitaire. Choix conservés pendant six mois et modifiables via « Confidentialité et cookies ».</p><a href="/confidentialite">Lire la notice de confidentialité</a><div className="dashboard-actions"><button className="secondary" onClick={()=>save({analytics:false,ads:false})}>Tout refuser</button><button className="secondary" onClick={()=>save({analytics:true,ads:true})}>Tout accepter</button><button onClick={()=>save({analytics,ads})}>Enregistrer mes choix</button></div></dialog>;
}
