import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {api} from './api';
import {dashboardModel,dashboardCsv,stages} from './dashboard-engine';
import Acquisition from './Acquisition';
import DealerOverview from './DealerOverview';
import './dashboard.css';
const date=value=>value?new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Paris'}).format(new Date(Number(value)*1000)):'À programmer';
export default function Dashboard({app:a,source=api,demo=false}){
 const admin=a.user?.role==='admin';
 const [params,setParams]=useSearchParams();
 const requestedTab=params.get('vue');
 const tab=['overview','leads','performance',...(admin?['network','acquisition']:[])].includes(requestedTab)?requestedTab:'overview';
 const setTab=value=>setParams(old=>{const next=new URLSearchParams(old);next.set('vue',value);return next;});
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[days,setDays]=useState(30),[dealer,setDealer]=useState(''),[includeDemo,setIncludeDemo]=useState(false),[query,setQuery]=useState(''),[status,setStatus]=useState('Tous'),[page,setPage]=useState(1),[stamp,setStamp]=useState(0);
 const request=useRef(0);
 async function load(){const id=++request.current;setBusy(true);setError('');try{const [leads,offers,users]=await Promise.all([source('/leads'),source('/pilot/inventory'),admin?source('/admin/users'):Promise.resolve([])]);if(request.current===id){setData({leads,offers,users});setStamp(Date.now());}}catch(e){if(request.current===id)setError(e.message);}finally{if(request.current===id)setBusy(false);}}
 useEffect(()=>{setData(null);load();return()=>{request.current++;};},[a.user?.id,admin,source]);
 useEffect(()=>{setPage(1);},[query,status,days,dealer,includeDemo]);
 const model=useMemo(()=>dashboardModel({...data,days,dealer,includeDemo,now:(stamp||Date.now())/1000}),[data,days,dealer,includeDemo,stamp]);
 const modelName=slug=>{const v=a.vehicles.find(v=>v.slug===slug);return v?`${v.brand} ${v.model}`:slug;};
 const dealerName=id=>a.dealers.find(d=>String(d.id)===String(id))?.name||'Établissement non renseigné';
 const filtered=model.current.filter(l=>(status==='Tous'||l.status===status)&&[l.name,modelName(l.vehicle_slug),dealerName(l.dealer_id)].join(' ').toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr'))).sort((x,y)=>Number(y.created)-Number(x.created));
 function download(){const url=URL.createObjectURL(new Blob([dashboardCsv(model)],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`volteo-indicateurs-${days}j.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <main className="container dashboard"><div className="dashboard-heading"><div><div className="eyebrow">{admin?'VOLTÉO / ADMINISTRATION':'VOLTÉO / PROFESSIONNELS'}</div><h1>{admin?'Le centre de pilotage.':'Votre concession, en mouvement.'}</h1><p>{admin?'Priorisez les actions et suivez le réseau.':`${a.user?.company||'Votre établissement'} · Vos demandes, vos essais, vos offres.`}</p></div><div className="dashboard-actions"><button className="secondary" disabled={busy} onClick={load}>{busy?'Actualisation…':'Actualiser ↻'}</button><button className="secondary" disabled={!data} onClick={download}>Exporter les indicateurs</button></div></div>
 {demo&&<p className="notice">Démonstration locale · données fictives · aucune modification de comptes réels.</p>}
 <div className="dashboard-tabs" role="group" aria-label="Vues du tableau de bord">{[['overview',admin?'Vue d’ensemble':'Ma journée'],['leads','Demandes et agenda'],...(!admin?[['performance','Performance']]:[]),...(admin?[['network','Réseau et accès'],['acquisition','SEO & SEA']]:[])].map(([id,label])=><button key={id} className={tab===id?'':'secondary'} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='acquisition'?<Acquisition/>:<><div className="dashboard-filters">{(admin||tab!=='overview')&&<label>Période des demandes<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90].map(n=><option key={n} value={n}>{n} derniers jours</option>)}</select></label>}{admin&&<label>Établissement<select value={dealer} onChange={e=>setDealer(e.target.value)}><option value="">Tout le réseau</option>{a.dealers.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>}<label className="checkbox"><input type="checkbox" checked={includeDemo} onChange={e=>setIncludeDemo(e.target.checked)}/>Inclure les demandes de démonstration</label></div>
 {error&&<p role="alert" className="notice">{error} <button className="text-button" onClick={load}>Réessayer</button>{data&&' Les derniers chiffres affichés peuvent être périmés.'}</p>}
 {!data?<p role="status">{error?'Les indicateurs ne sont pas disponibles.':'Chargement des indicateurs…'}</p>:<><p className="dashboard-stamp">Actualisé le {date(stamp/1000)} · {!includeDemo?`${model.demoCount} demande(s) de démonstration exclue(s)`:'Démonstration incluse'} · Fuseau Europe/Paris</p>
 {!admin&&tab==='overview'&&<DealerOverview model={model} modelName={modelName} onAgenda={()=>setTab('leads')} onPerformance={()=>setTab('performance')} preview={()=>a.professionalView?.switchView()}/>}{(admin||tab!=='overview')&&<div className="dashboard-kpis">{[
 ['Demandes reçues',model.current.length,model.delta===null?'Pas de base de comparaison':`${model.delta>=0?'+':''}${model.delta} % vs période précédente`],
 ['À relancer',model.urgent.length,'Sans évolution depuis 48 h · tous âges'],
 ['Essais à venir',model.agenda.length,'Créneaux futurs · toutes demandes'],
 ['Présences confirmées',model.attended,`Sur les demandes reçues en ${days} jours`]
 ].map(([label,value,detail])=><article className="dashboard-kpi" key={label}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div>}
 {(admin&&tab==='overview'||tab==='performance')&&<><div className="dashboard-grid"><section className="panel"><div className="eyebrow">DEMANDES REÇUES</div><h2>Le rythme de votre activité.</h2><p className="muted">{Math.min(days,30)} derniers jours · nombre de demandes par jour</p><div className="dashboard-trend" role="img" aria-label={`${model.current.length} demandes reçues sur ${days} jours. Graphique détaillé dans le tableau ci-dessous.`}>{model.trend.map(day=><div key={day.key} title={`${day.label} : ${day.value}`}><i style={{height:`${day.value?Math.max(4,day.value/Math.max(1,...model.trend.map(x=>x.value))*100):0}%`}}/><small>{day.label}</small></div>)}</div><details><summary>Lire les valeurs du graphique</summary><table><caption>Demandes reçues par jour</caption><thead><tr><th>Date</th><th>Demandes</th></tr></thead><tbody>{model.trend.map(d=><tr key={d.key}><td>{d.label}</td><td>{d.value}</td></tr>)}</tbody></table></details></section><section className="panel"><div className="eyebrow">RÉPARTITION ACTUELLE</div><h2>Où en sont les demandes ?</h2>{model.counts.map((s,i)=><div className="dashboard-stage" key={s.label}><span><i style={{background:['var(--cyan)','var(--green)','#d7b875','#a394f5','#89949b'][i]}}/>{s.label}</span><b>{s.value}</b><meter min="0" max={Math.max(1,model.current.length)} value={s.value} aria-label={s.label}/></div>)}<p className="muted">Statuts actuels des demandes de la période. Un essai terminé n’est pas une vente.</p></section></div>
 <section className="panel"><div className="section-heading"><h2>À traiter en priorité.</h2><button className="secondary" onClick={()=>setTab('leads')}>Voir les demandes →</button></div><div className="dashboard-priorities"><div><strong>{model.urgent.length}</strong><span>Demandes sans évolution depuis 48 h</span></div><div><strong>{model.missed.length}</strong><span>Essais passés à mettre à jour</span></div><Link to="/stock"><strong>{model.expired.length+model.expiring.length}</strong><span>Offres expirées ou à reconfirmer sous 48 h →</span></Link></div></section></>}
 {tab==='leads'&&<><div className="dashboard-grid"><section className="panel"><h2>Les prochains essais.</h2>{model.agenda.length?model.agenda.slice(0,8).map(l=><Link className="dashboard-row" key={l.id} to={'/professionnel?lead='+encodeURIComponent(l.id)}><span><b>{l.name}</b><small>{modelName(l.vehicle_slug)}</small></span><span>{date(l.appointment)} →</span></Link>):<p>Aucun essai à venir. Planifiez un créneau depuis une demande.</p>}</section><section className="panel"><h2>Vos relances prioritaires.</h2>{model.urgent.length?model.urgent.slice(0,8).map(l=><Link className="dashboard-row" key={l.id} to={'/professionnel?lead='+encodeURIComponent(l.id)}><span><b>{l.name}</b><small>{modelName(l.vehicle_slug)}</small></span><span>{l.status} →</span></Link>):<p>Aucune demande en attente depuis plus de 48 h.</p>}</section></div><section className="panel"><h2>Les demandes de la période.</h2><div className="dashboard-filters"><label>Rechercher<input type="search" placeholder="Nom, modèle, établissement" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Statut<select value={status} onChange={e=>setStatus(e.target.value)}>{['Tous',...stages].map(s=><option key={s}>{s}</option>)}</select></label></div><div className="table-scroll"><table><thead><tr><th>Contact</th><th>Véhicule</th>{admin&&<th>Établissement</th>}<th>Statut</th><th>Reçue le</th><th>Action</th></tr></thead><tbody>{filtered.slice((page-1)*10,page*10).map(l=><tr key={l.id}><td>{l.name}</td><td>{modelName(l.vehicle_slug)}</td>{admin&&<td>{dealerName(l.dealer_id)}</td>}<td><span className="pill">{l.status}</span></td><td>{date(l.created)}</td><td><Link to={'/professionnel?lead='+encodeURIComponent(l.id)}>Ouvrir →</Link></td></tr>)}</tbody></table></div>{!filtered.length&&<p>Aucune demande pour ces filtres.</p>}<div className="dashboard-actions"><button className="secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Précédent</button><span>{filtered.length} résultat(s) · page {page} / {Math.max(1,Math.ceil(filtered.length/10))}</span><button className="secondary" disabled={page*10>=filtered.length} onClick={()=>setPage(p=>p+1)}>Suivant</button></div></section></>}
 {tab==='network'&&<div className="dashboard-grid"><section className="panel"><h2>Comptes pros à vérifier.</h2><p>{model.pendingUsers.length} compte(s) professionnel(s) sans accès concessionnaire.</p>{model.pendingUsers.slice(0,10).map(u=><div className="dashboard-row" key={u.id}><span><b>{u.company||u.name}</b><small>{u.name} · {u.postcode}</small></span><span>En attente</span></div>)}<Link className="button secondary" to="/admin/gestion">Gérer les rôles et partenaires →</Link></section><section className="panel"><h2>Demandes par établissement.</h2>{model.byDealer.length?model.byDealer.map(d=><div className="dashboard-row" key={d.id}><span>{dealerName(d.id)}</span><b>{d.value}</b></div>):<p>Aucune demande dans cette période.</p>}<Link className="button secondary" to="/stock">Contrôler les offres →</Link></section></div>}
 <div className="dashboard-actions"><Link className="button" to="/professionnel">Traiter les demandes →</Link><Link className="button secondary" to="/stock">Gérer les offres</Link>{admin&&<Link className="button secondary" to="/admin/gestion">Comptes, catalogue et partenaires</Link>}</div>
 </>}
 </>}
 </main>;
}
