import React from 'react';
import {Link} from 'react-router-dom';
export default function DataSources(){return <main className="container"><div className="eyebrow">SOURCES ET ACTUALISATION</div><h1>Une donnée utile.<br/>Une date visible.</h1><p className="intro">VOLTÉO distingue les derniers relevés disponibles, les déclarations des professionnels et les hypothèses de simulation. Consulter une source aujourd’hui ne signifie pas que toutes ses informations ont été modifiées aujourd’hui.</p><div className="grid">{[
 ['Prix des carburants','Flux officiel connecté','Les relevés déclarés par les stations sont recherchés automatiquement toutes les 10 minutes lorsque la carte est ouverte. La date du prix reste visible ; un prix de plus de 7 jours ne peut pas être importé dans le simulateur.','https://data.economie.gouv.fr/explore/dataset/prix-des-carburants-en-france-flux-instantane-v2/'],
 ['Points de recharge','Base nationale IRVE connectée','Caractéristiques issues de la base nationale. Après une recherche, les statuts sont actualisés chaque minute sur la page Recharge. Un statut de plus de 5 minutes devient inconnu. Couverture partielle, pas de réservation ni de garantie de disponibilité.','https://www.data.gouv.fr/datasets/beta-bases-nationales-des-points-de-recharge-pour-vehicules-electriques-en-france-irve'],
 ['Offres locales','Déclarations des partenaires','La liste est relue chaque minute lorsqu’elle est affichée. Les offres expirent au plus tard 7 jours après confirmation. Le stock physique n’est pas connecté à un logiciel de concession.','/offres-locales'],
 ['Véhicules et caractéristiques','Catalogue de démonstration','Les prix, autonomies et caractéristiques du catalogue ne constituent pas des tarifs constructeurs actuels. Aucun flux constructeur n’est raccordé. Utilisez une offre partenaire datée ou demandez un devis avant toute décision.','/catalogue'],
 ['Électricité, financement et économies','Hypothèses personnelles','Renseignez vos tarifs contractuels et votre devis. Les taux, frais, valeurs de revente et projections du simulateur ne sont pas des cotations en direct. Les actualisations ne modifient pas vos saisies ni vos simulations enregistrées.','/simulateur'],
 ['Guides et concessions','Contenus à vérifier','Les guides sont éditoriaux, sans veille automatique. La présence d’une concession dans OpenStreetMap ne prouve ni son partenariat, ni son stock, ni ses horaires du jour.','/autour-de-moi']
 ].map(([title,status,body,href])=><section className="panel" key={title}><span className="pill">{status}</span><h2>{title}</h2><p>{body}</p>{href.startsWith('/')?<Link to={href}>Consulter →</Link>:<a href={href} target="_blank" rel="noreferrer">Source officielle ↗</a>}</section>)}</div></main>;}
