import React from 'react';
import {Link} from 'react-router-dom';

const time=t=>new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Paris'}).format(new Date(t*1000));
export default function DealerOverview({model,modelName,onAgenda,onPerformance,preview}){
 const published=model.inventory.filter(o=>o.status==='published'&&!model.expired.includes(o));
 const newLeads=model.open.filter(l=>l.status==='Nouveau');
 const queue=[...model.urgent,...newLeads.filter(l=>!model.urgent.some(u=>u.id===l.id))].slice(0,5);
 return <div className="dealer-overview">
  <section className="dealer-focus"><div><span className="eyebrow">VOTRE PROCHAINE ACTION</span><h2>{model.urgent.length?'Reprenez contact avec vos prospects.':newLeads.length?'Un premier échange à préparer.':'Gardez une longueur d’avance.'}</h2><p>{model.urgent.length?`${model.urgent.length} demande(s) sans évolution depuis au moins 48 heures.`:newLeads.length?`${newLeads.length} nouvelle(s) demande(s) à examiner.`:'Vérifiez vos disponibilités et préparez les prochains essais.'}</p><Link className="button" to={queue[0]?'/professionnel?lead='+encodeURIComponent(queue[0].id):'/stock'}>{queue[0]?'Ouvrir la demande prioritaire':'Vérifier mes offres'} →</Link></div><div className="dealer-focus-note"><span>LE BON RÉFLEXE</span><p>Consultez les besoins partagés, contactez le client, puis convenez ensemble du créneau.</p><small>Un changement de statut n’envoie pas de message automatique.</small></div></section>
  <div className="dealer-work-grid"><section className="panel"><div className="dealer-section-title"><div><span className="eyebrow">RELATION CLIENT</span><h2>À contacter.</h2></div><Link to="/professionnel">Toutes les demandes ↗</Link></div>{queue.length?queue.map(l=><Link key={l.id} className="dashboard-row" to={'/professionnel?lead='+encodeURIComponent(l.id)}><span><b>{l.name}</b><small>{modelName(l.vehicle_slug)}</small></span><span className="pill">{model.urgent.includes(l)?'Relance à prévoir':l.status} →</span></Link>):<div className="dealer-empty"><b>Votre liste est à jour.</b><p>Les nouvelles demandes et les relances apparaîtront ici.</p></div>}</section>
  <section className="panel"><div className="dealer-section-title"><div><span className="eyebrow">AGENDA</span><h2>Prochains essais.</h2></div><button className="text-button" onClick={onAgenda}>Voir l’agenda ↗</button></div>{model.agenda.length?model.agenda.slice(0,4).map(l=><Link key={l.id} className="dashboard-row" to={'/professionnel?lead='+encodeURIComponent(l.id)}><span><b>{time(l.appointment)}</b><small>{l.name} · {modelName(l.vehicle_slug)}</small></span><span>Préparer →</span></Link>):<div className="dealer-empty"><b>Aucun essai programmé.</b><p>Proposez un créneau au client depuis sa demande, après avoir convenu de sa disponibilité.</p></div>}{model.missed.length>0&&<Link className="dealer-alert" to="/professionnel">{model.missed.length} essai(s) passé(s) à mettre à jour →</Link>}</section></div>
  <div className="dealer-work-grid"><section className="panel"><span className="eyebrow">VITRINE COMMERCIALE</span><h2>Des offres fiables et à jour.</h2><div className="dealer-stock-counts"><div><strong>{published.length}</strong><span>publiées, non expirées</span></div><div><strong>{model.expiring.length}</strong><span>expirent sous 48 h</span></div><div><strong>{model.expired.length}</strong><span>expirées</span></div></div><p className="muted">La visibilité publique dépend aussi de la validation du partenaire. Confirmez le prix, la finition et la disponibilité réelle.</p><Link className="button secondary" to="/stock">Gérer le stock et les offres →</Link></section>
  <section className="panel dealer-client-tools"><span className="eyebrow">EN RENDEZ-VOUS</span><h2>Accompagnez le choix du client.</h2><p>Passez côté acheteur pour explorer les modèles, comparer une sélection adaptée et expliquer le coût de possession.</p><button className="secondary" onClick={preview}>Ouvrir la vue acheteur ↗</button><small>Vos accès professionnels restent actifs. Revenez ici en un clic.</small><button className="text-button" onClick={onPerformance}>Consulter mes indicateurs d’activité →</button></section></div>
 </div>;
}
