import React,{useEffect,useId,useRef} from 'react';
import {Link,useLocation} from 'react-router-dom';

export function Icon({name,size=20}){
 const paths={home:<><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/></>,car:<><path d="m5 7 2-4h10l2 4 2 3v8H3v-8l2-3Zm0 0h14M3 13h18M6 18v3m12-3v3M6 10h2m8 0h2"/></>,passport:<><rect x="5" y="3" width="15" height="18" rx="3"/><path d="M8 3v18m4-13h4m-4 4h4m-4 4h2"/></>,map:<><path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,bolt:<path d="m13 2-9 12h7l-1 8 10-13h-7l1-7Z"/>,wallet:<><rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 8V5l13-3v3m5 7h-6v5h6m-3-2h.01"/></>,user:<><circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></>,menu:<><path d="M4 6h16M4 12h16M4 18h16"/></>,close:<path d="m6 6 12 12M6 18 18 6"/>,arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,back:<path d="M20 12H4m6-6-6 6 6 6"/>,book:<><path d="M12 5v16M3 4h5l4 2 4-2h5v15h-5l-4 2-4-2H3Z"/></>,sun:<><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.4 1.4m11.2 11.2L19 19M5 19l1.4-1.4M17.6 6.4 19 5"/></>,moon:<path d="M20.8 13.3A9 9 0 0 1 10.7 3.2 9 9 0 1 0 20.8 13.3Z"/>,shield:<><path d="m12 2 8 3v6c0 5-8 11-8 11S4 16 4 11V5Z"/><path d="m8 11 3 3 5-5"/></>,compare:<><path d="M8 3v18M16 3v18M4 7h8m0 10h8"/><circle cx="8" cy="7" r="2"/><circle cx="16" cy="17" r="2"/></>,offers:<><path d="M3 4h8l10 10-7 7L3 10Z"/><circle cx="7" cy="8" r="1"/></>};
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.arrow}</svg>;
}

export function Field({label,children,help}){
 const id=useId(),required=React.isValidElement(children)&&children.props.required;
 return <label className="field" htmlFor={id}><span className="field-label">{label}{required&&<span className="required-dot" aria-hidden="true"> *</span>}</span>{React.isValidElement(children)?React.cloneElement(children,{id,'aria-label':label,...(help?{'aria-describedby':id+'-help'}:{})}):children}{help&&<small id={id+'-help'}>{help}</small>}</label>;
}

const buyerLinks=[['/catalogue','Véhicules','car'],['/passeport','Mon passeport','passport'],['/offres-locales','Offres locales','offers'],['/recharge','Recharge','bolt'],['/simulateur','Mon budget','wallet']];
const discoveryLinks=[['/pilote','Le pilote des Ulis','map'],['/autour-de-moi','Carte et proximité','map'],['/comparateur','Comparer les véhicules','compare'],['/guides','Guides pratiques','book'],['/diagnostic','Diagnostic rapide','bolt'],['/projet','Mon projet détaillé','passport']];
const proLinks=[['/professionnel','Demandes','passport'],['/stock','Mes offres','car'],['/compte','Établissement','user'],['/pilote','Le pilote','map']];
function active(path,to){return path===to||(to==='/catalogue'&&path.startsWith('/vehicules/'))||(to==='/passeport'&&['/projet','/diagnostic'].includes(path));}

export function AppHeader({app:a,menu,setMenu,theme,setTheme}){
 const loc=useLocation(),dialog=useRef(null),canManage=['dealer','admin'].includes(a.user?.role),links=a.isPro?proLinks.filter(x=>x[0]!=='/stock'||canManage):buyerLinks;
 useEffect(()=>{const el=dialog.current;if(menu&&!el.open)el.showModal();else if(!menu&&el.open)el.close();},[menu]);
 useEffect(()=>{if(!menu)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[menu]);
 useEffect(()=>{if(!menu)return;const el=dialog.current;const trap=e=>{if(e.key!=='Tab')return;const items=[...el.querySelectorAll('a[href],button:not([disabled]),[tabindex="0"]')].filter(x=>x.getClientRects().length);const first=items[0],last=items.at(-1);if((e.shiftKey&&document.activeElement===first)||(!e.shiftKey&&document.activeElement===last)){e.preventDefault();(e.shiftKey?last:first)?.focus();}};el.addEventListener('keydown',trap);return()=>el.removeEventListener('keydown',trap);},[menu]);
 const link=([to,label,icon],drawer=false)=><Link key={to} to={to} className={active(loc.pathname,to)?'active':''} aria-current={active(loc.pathname,to)?'page':undefined} onClick={()=>setMenu(false)}>{drawer&&<Icon name={icon}/>}<span>{label}</span>{drawer&&<Icon name="arrow" size={16}/>}</Link>;
 return <><header className="app-header"><Link className="brand" to="/" aria-label="VOLTÉO — Accueil">VOLTÉO<span><Icon name="bolt" size={20}/></span></Link><nav className="desktop-nav" aria-label="Navigation principale">{links.map(x=>link(x))}</nav><div className="header-tools"><button className="theme-toggle" aria-label={theme==='dark'?'Activer le thème clair':'Activer le thème sombre'} onClick={()=>setTheme(theme==='dark'?'light':'dark')}><Icon name={theme==='dark'?'sun':'moon'}/></button><Link className="account-link" to={a.user?'/compte':'/connexion'}><span className="account-avatar" aria-hidden="true">{a.user?a.user.name[0].toUpperCase():<Icon name="user" size={17}/>}</span><span>{a.user?a.user.name.split(' ')[0]:'Mon espace'}</span></Link><button className="explore-toggle" aria-label="Ouvrir le menu" aria-haspopup="dialog" aria-expanded={menu} onClick={()=>setMenu(true)}><Icon name="menu"/><span>Explorer</span></button></div></header><dialog ref={dialog} className="menu-dialog" aria-labelledby="menu-title" onCancel={()=>setMenu(false)} onClose={()=>setMenu(false)} onClick={e=>{if(e.target===e.currentTarget)setMenu(false);}}><div className="menu-content"><div className="menu-heading"><div><span className="eyebrow">VOTRE ESPACE VOLTÉO</span><h2 id="menu-title">Où souhaitez-vous aller ?</h2></div><button className="icon-button" aria-label="Fermer le menu" onClick={()=>setMenu(false)}><Icon name="close"/></button></div><nav className="drawer-nav" aria-label="Toutes les rubriques"><section><h3>{a.isPro?'Mon activité':'Mon parcours électrique'}</h3>{links.map(x=>link(x,true))}{a.user?.role==='admin'&&link(['/admin','Administration','shield'],true)}{a.isPro&&link(['/simulateur','Outil budget','wallet'],true)}</section><section><h3>Explorer et comprendre</h3>{(a.isPro?buyerLinks.filter(x=>x[0]!=='/passeport'&&x[0]!=='/simulateur'):discoveryLinks).map(x=>link(x,true))}{!a.isPro&&link(['/partenaires','Devenir partenaire','user'],true)}{link([a.user?'/parametres':'/connexion',a.user?'Paramètres et sécurité':'Connexion / inscription','shield'],true)}</section></nav><div className="menu-local"><Icon name="map"/><p><b>Pilote Les Ulis · {a.pilot.radius} km</b><span>Votre accompagnement électrique commence près de chez vous.</span></p></div></div></dialog></>;
}

export function MobileNav({app:a,onMenu}){
 const {pathname}=useLocation(),canManage=['dealer','admin'].includes(a.user?.role);
 const links=a.isPro?[['/professionnel','Demandes','passport'],[canManage?'/stock':'/compte',canManage?'Offres':'Compte',canManage?'car':'user'],['/pilote','Pilote','map']]:[['/catalogue','Véhicules','car'],['/passeport','Projet','passport'],['/offres-locales','Offres','offers']];
 return <nav className="mobile-tabbar" aria-label="Navigation rapide">{links.map(([to,label,icon])=><Link key={to} to={to} aria-current={active(pathname,to)?'page':undefined} className={active(pathname,to)?'active':''}><Icon name={icon}/><span>{label}</span></Link>)}<button onClick={onMenu} aria-label="Ouvrir toutes les rubriques" aria-haspopup="dialog"><Icon name="menu"/><span>Plus</span></button></nav>;
}

const labels={'/catalogue':'Véhicules','/passeport':'Mon passeport','/offres-locales':'Offres locales','/recharge':'Plan de recharge','/simulateur':'Mon budget','/pilote':'Pilote Les Ulis','/projet':'Mon projet','/diagnostic':'Diagnostic','/comparateur':'Comparateur','/autour-de-moi':'Autour de moi','/connexion':'Mon espace','/compte':'Mon compte','/professionnel':'Demandes d’essai','/stock':'Mes offres','/admin':'Administration','/partenaires':'Professionnels','/parametres':'Paramètres','/guides':'Guides pratiques','/confidentialite':'Confidentialité','/credits-photos':'Crédits photos'};
export function RouteTools({app:a}){
 const {pathname}=useLocation(),label=labels[pathname]||(pathname.startsWith('/vehicules/')?'Fiche véhicule':'VOLTÉO');
 useEffect(()=>{document.title='VOLTÉO · '+(pathname==='/'?'Votre prochain départ':label);},[pathname,label]);
 if(pathname==='/')return null;
 const stage=['/passeport','/projet','/diagnostic','/recharge'].includes(pathname)?0:['/catalogue','/simulateur','/comparateur'].includes(pathname)?1:pathname==='/offres-locales'||pathname.startsWith('/vehicules/')?2:null;
 return <div className="route-tools"><div className="breadcrumb"><Link to="/"><Icon name="home" size={15}/><span>Accueil</span></Link><span aria-hidden="true">/</span><span aria-current="page">{label}</span></div>{!a.isPro&&stage!==null&&<nav className="journey-nav" aria-label="Étapes de votre projet">{[['/passeport','Mon quotidien'],['/catalogue','Mes modèles'],['/offres-locales','Mon essai']].map(([to,text],i)=><Link key={to} to={to} className={stage===i?'current':''} aria-current={stage===i?'step':undefined}><span>{i+1}</span>{text}</Link>)}</nav>}<span className="sr-only" role="status">Page : {label}</span></div>;
}

export function Footer(){return <footer className="app-footer"><div className="footer-intro"><Link className="brand" to="/">VOLTÉO<span><Icon name="bolt"/></span></Link><p>Votre quotidien.<br/>Votre prochaine électrique.</p><span className="pill">Le pilote commence aux Ulis</span></div><div className="footer-group"><h2>Votre projet</h2><Link to="/passeport">Passeport électrique</Link><Link to="/catalogue">Catalogue de véhicules</Link><Link to="/simulateur">Coût total</Link><Link to="/recharge">Plan de recharge</Link></div><div className="footer-group"><h2>Tout près de vous</h2><Link to="/pilote">Participer au pilote</Link><Link to="/offres-locales">Offres locales</Link><Link to="/autour-de-moi">Carte interactive</Link><Link to="/partenaires">Devenir partenaire</Link></div><div className="footer-bottom"><span>Les estimations ne remplacent pas un devis. Les données non vérifiées restent signalées.</span><Link to="/confidentialite">Confidentialité</Link><Link to="/mentions-legales">Mentions légales</Link><Link to="/conditions">Conditions</Link><Link to="/credits-photos">Crédits photos</Link></div></footer>;}

const groups=[{title:'Votre rythme',text:'Le kilométrage est partagé avec votre projet.',keys:['km','years'],open:true},{title:'Énergie et recharge',text:'Ajustez les prix à votre situation et votre accès à la recharge.',keys:['fuel','liters','homeRate','publicRate','homeShare'],open:true},{title:'Achat et valeur de revente',text:'Ces valeurs sont des hypothèses : elles ne constituent pas une offre.',keys:['thermalValue','thermalResale','electricResale','installation']},{title:'Financement envisagé',text:'La mensualité de crédit est distincte du coût total de possession.',keys:['deposit','months','apr']},{title:'Entretien et assurance',text:'Affinez avec vos devis et dépenses annuelles.',keys:['thermalMaintenance','electricMaintenance','thermalInsurance','electricInsurance']}];
export function SimulatorFields({fields,render}){return <div className="form-sections">{groups.map((group,i)=><details className="form-section" key={group.title} open={group.open}><summary><span className="section-index">0{i+1}</span><span><b>{group.title}</b><small>{group.text}</small></span><span className="disclosure-icon" aria-hidden="true">+</span></summary><div className="form-grid">{fields.filter(f=>group.keys.includes(f[0])).map(render)}</div></details>)}</div>;}
