import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {Field} from './Experience';
import {useFormDraft} from './journey';
import {energyStudyDefaults,energyOrientation,installationBudget} from './home-energy';
import './home-energy.css';
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const labels={housing:{unknown:'À préciser',house:'Maison',flat:'Appartement'},tenure:{unknown:'À préciser',owner:'Propriétaire',tenant:'Locataire / occupant'},parking:{unknown:'À préciser',yes:'Oui, une place dédiée',no:'Non'},daytime:{unknown:'À préciser',yes:'Souvent',sometimes:'Parfois',no:'Rarement'},solar:{unknown:'À préciser',installed:'Déjà installés',interested:'À étudier',no:'Pas de projet solaire'}};
export default function HomeEnergy({app:a}){
 const [stored,setStored]=useFormDraft(a,'homeEnergy',energyStudyDefaults),p={...energyStudyDefaults,...stored},[message,setMessage]=useState('');
 const orientation=energyOrientation(p),budget=installationBudget(p);
 function patch(value){setStored({...p,...value});setMessage('');}
 function choice(key,label){return <Field label={label}><select value={p[key]} onChange={e=>patch({[key]:e.target.value})}>{Object.entries(labels[key]).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></Field>;}
 const request=`Bonjour, je souhaite étudier une solution de recharge à domicile.\nLogement : ${labels.housing[p.housing]}. Statut : ${labels.tenure[p.tenure]}. Stationnement : ${labels.parking[p.parking]}.\nKilométrage déclaré : ${a.buyer.km} km/an. Présence de la voiture en journée : ${labels.daytime[p.daytime]}. Solaire : ${labels.solar[p.solar]}.\nMerci de détailler la puissance adaptée au véhicule et à mes horaires, le pilotage, les protections, le câblage, les travaux, le prix TTC posé, les frais récurrents, la garantie et les aides effectivement accessibles. ${p.solar==='interested'?'Je souhaite aussi une étude solaire distincte, avec ses hypothèses de production et de consommation.':''}\nLe modèle du véhicule, l’adresse et les caractéristiques électriques seront à compléter avant le devis.`;
 async function copy(){try{await navigator.clipboard.writeText(request);setMessage('Demande copiée. Vous choisissez à qui la transmettre.');}catch{setMessage('Copie indisponible : sélectionnez le texte de la demande ci-dessous.');}}
 function applyBudget(){if(!budget)return;a.setDraft('simulator',old=>({...old,installation:budget.net}));setMessage('Coût net de pose reporté dans le brouillon de Mon budget. Les simulations déjà enregistrées restent inchangées.');}
 return <section className="home-energy panel" id="recharge-domicile" aria-labelledby="home-energy-title"><div className="eyebrow">BORNE À DOMICILE · SOLAIRE EN OPTION</div><h2 id="home-energy-title">Recharger chez vous, au juste coût.</h2><p>Identifiez les pistes adaptées à votre logement. Une orientation prépare une étude ; elle ne confirme ni la faisabilité, ni une aide, ni une économie.</p><div className="energy-layout"><div><div className="form-grid">{choice('housing','Votre logement')}{choice('tenure','Vous êtes')}{choice('parking','Disposez-vous d’une place de stationnement dédiée ?')}{choice('daytime','Votre voiture est-elle à domicile en journée ?')}{choice('solar','Panneaux photovoltaïques')}</div><button className="text-button" onClick={()=>{setStored(energyStudyDefaults);setMessage('Les réponses de cette étude ont été réinitialisées.');}}>Réinitialiser cette étude</button></div><aside className="energy-orientation" aria-live="polite"><span className="pill">Orientation selon vos réponses</span><h3>{orientation.title}</h3><p>{orientation.body}</p>{p.tenure==='tenant'&&p.parking==='yes'&&<p>Clarifiez les démarches avec le propriétaire ou le bailleur avant tout engagement.</p>}<Link to="/catalogue">Choisir un véhicule pour préciser le besoin →</Link></aside></div>
 <details className="energy-details" open><summary>Les pistes pour maîtriser votre budget</summary><ul><li><b>Une puissance adaptée.</b> Comparez votre besoin quotidien, le temps de stationnement et la limite de recharge du véhicule avant de choisir une borne.</li><li><b>Un devis complet.</b> Comparez borne, pose, protections, longueur de câble, travaux, garanties et frais récurrents.</li><li><b>Le pilotage.</b> Étudiez la modulation de puissance avant d’augmenter votre abonnement électrique.</li><li><b>Les bons créneaux.</b> Comparez la facture totale du foyer, abonnement compris, puis programmez la recharge selon vos horaires contractuels. Les heures creuses ne sont pas automatiquement avantageuses pour tous.</li></ul><a href="https://www.enedis.fr/je-veux-recharger-mon-vehicule-electrique-sur-mon-lieu-de-residence" target="_blank" rel="noreferrer">Conseils Enedis et démarches ↗</a></details>
 <details className="energy-details"><summary>Aides et coût de pose · sources vérifiées le 10/10/2026</summary>{orientation.advenir?<p><b>Advenir : une piste à vérifier.</b> En immeuble collectif, sur une place dédiée, l’aide individuelle peut atteindre 50 % de la fourniture et pose HT, plafonnée à 1 000 € par point de recharge, sous conditions. Votre réponse au formulaire ne constitue pas une validation d’éligibilité.</p>:<p>Advenir ne finance pas les bornes en maison individuelle. En immeuble collectif, précisez votre stationnement pour examiner cette piste.</p>}<p>Le crédit d’impôt pour les bornes est supprimé pour les dépenses payées à partir du 1er janvier 2026. Aucune aide n’est déduite automatiquement. Vérifiez également les éventuels dispositifs locaux avant signature.</p><div className="actions"><a href="https://advenir.mobi/borne-individuelle/" target="_blank" rel="noreferrer">Conditions Advenir ↗</a><a href="https://www.service-public.gouv.fr/particuliers/vosdroits/F35578" target="_blank" rel="noreferrer">Crédit d’impôt : dates et conditions ↗</a></div><p className="muted">Informations éditoriales datées, sans actualisation automatique. Les conditions peuvent évoluer.</p><div className="form-grid"><Field label="Devis complet de pose TTC (€)"><input type="number" min="0" step="1" value={p.quote} placeholder="À renseigner après devis" onChange={e=>patch({quote:e.target.value,aidConfirmed:false})}/></Field><Field label="Aides confirmées pour ce devis (€)"><input type="number" min="0" step="1" value={p.aid} onChange={e=>patch({aid:e.target.value,aidConfirmed:false})}/></Field></div><label className="energy-check"><input type="checkbox" checked={p.aidConfirmed} onChange={e=>patch({aidConfirmed:e.target.checked})}/>J’ai vérifié l’éligibilité et le montant des aides pour ce devis.</label>{budget?<><p><b>{euro(budget.net)} de coût net de pose</b> · devis {euro(budget.quote)} − aides confirmées {euro(budget.aid)}.</p><p className="muted">Une aide remboursée ultérieurement peut nécessiter d’avancer le prix total du devis. Abonnements et financement ne sont pas inclus dans ce montant.</p><button className="secondary" onClick={applyBudget}>Reporter ce coût dans Mon budget</button></>:<p className="muted">Renseignez un devis positif ou nul ; les aides confirmées ne peuvent pas dépasser son montant.</p>}<p><Link to="/simulateur">Ouvrir Mon budget →</Link></p></details>
 {p.solar!=='no'&&<details className="energy-details"><summary>Le solaire peut-il contribuer à ma recharge ?</summary><p>{orientation.solar}</p><p>{p.daytime==='no'?'Votre voiture est rarement présente en journée : ne supposez pas que la production solaire couvrira directement sa recharge nocturne.':'La présence de la voiture pendant les heures de production peut favoriser la recharge solaire ; la production et les besoins varient selon la saison.'}</p><p>Demandez une étude séparée : investissement, production prévisionnelle, part consommée par le foyer et la voiture, surplus, entretien et financement. Les économies du logement ne doivent pas être attribuées entièrement à la voiture. Aucun gain solaire n’est ajouté au simulateur.</p><div className="actions"><a href="https://www.enedis.fr/particulier-tout-savoir-sur-lautoconsommation-collective" target="_blank" rel="noreferrer">Solaire collectif, y compris en appartement ↗</a><a href="https://www.ademe.fr/wp-content/uploads/2025/01/avis-ademe-autoconsommation-photovoltaique_-janvier-2025.pdf" target="_blank" rel="noreferrer">Avis ADEME sur l’autoconsommation ↗</a></div></details>}
 <details className="energy-details"><summary>Préparer ma demande à un installateur</summary><p>Le réseau d’installateurs VOLTÉO est en préparation. Aucun professionnel n’est présenté ici comme partenaire vérifié. Vous pouvez copier cette demande et choisir vous-même un installateur qualifié.</p><Field label="Modèle de demande à copier et compléter"><textarea readOnly rows={8} value={request}/></Field><div className="actions"><button className="secondary" onClick={copy}>Copier ma demande</button><a href="https://advenir.mobi/borne-individuelle/" target="_blank" rel="noreferrer">Consulter les démarches Advenir ↗</a></div><p className="muted">Aucune demande ni coordonnée n’est envoyée automatiquement. Vos réponses restent dans le brouillon de cette session.</p></details><p role="status" className="energy-status">{message}</p></section>;
}
