import React,{useState,useRef} from 'react';
import {Link} from 'react-router-dom';
import {api} from './api';
export default function LocationBar({app:a}){
 const [open,setOpen]=useState(false),[cities,setCities]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),generation=useRef(0);
 async function search(e){e.preventDefault();const request=++generation.current;setBusy(true);setMsg('');setCities([]);try{const found=await api('/location?postcode='+a.buyer.postcode);if(request!==generation.current)return;setCities(found);if(found.length===1)choose(found[0]);if(!found.length)setMsg('Aucune commune trouvée. Vérifiez votre code postal.');}catch(e){if(request===generation.current)setMsg(e.message);}finally{if(request===generation.current)setBusy(false);}}
 function choose(city){a.selectPlace({...city,postcode:a.buyer.postcode,approximate:true});setCities([]);setOpen(false);}
 function locate(){const request=++generation.current;if(!navigator.geolocation){setMsg('Localisation indisponible : utilisez le code postal.');return;}setBusy(true);setMsg('');navigator.geolocation.getCurrentPosition(p=>{if(request!==generation.current)return;a.selectPlace({name:'Ma position GPS',lat:p.coords.latitude,lon:p.coords.longitude,accuracy:Math.round(p.coords.accuracy),approximate:false});setBusy(false);setOpen(false);},()=>{if(request!==generation.current)return;setBusy(false);setMsg('Position indisponible ou refusée. Vous pouvez saisir un code postal.');},{enableHighAccuracy:false,timeout:10000,maximumAge:60000});}
 return <section className="context-bar" aria-label="Votre parcours et votre localisation"><div className="context-line"><span className="pill">{a.isPro?'Espace professionnel':'Parcours acheteur'}{a.user?.account_type==='pro'&&a.user.role==='user'?' · à valider':''}</span><button className="text-button" aria-expanded={open} onClick={()=>setOpen(!open)}>◎ {a.geoData.place?.name||a.buyer.postcode||'Définir ma localisation'} · Modifier</button><Link to={a.isPro?'/compte':'/passeport'}>{a.isPro?'Mon établissement':'Mon passeport'} →</Link></div>{open&&<div className="context-location"><form onSubmit={search}><label className="field"><span>Code postal de recherche</span><input required pattern="[0-9]{5}" inputMode="numeric" maxLength={5} value={a.buyer.postcode} onChange={e=>{generation.current++;setBusy(false);a.updateBuyer({postcode:e.target.value});setCities([]);}}/></label><button disabled={busy}>Choisir ma commune</button></form><button className="secondary" onClick={locate} disabled={busy}>Utiliser ma position GPS</button>{cities.length>1&&<label className="field"><span>Commune de recherche</span><select defaultValue="" onChange={e=>{const c=cities.find(c=>c.code===e.target.value);if(c)choose(c);}}><option value="">Choisir une commune</option>{cities.map(c=><option value={c.code} key={c.code}>{c.name}</option>)}</select></label>}<small>Cette zone suit votre navigation. Les coordonnées GPS ne sont pas enregistrées dans votre compte. Le code postal du dossier reste distinct d’une recherche GPS temporaire.</small>{busy&&<p role="status">Localisation en cours…</p>}{msg&&<p role="alert">{msg}</p>}</div>}</section>;
}
