import config from '../pilot-config.json' with {type:'json'};
export const pilotConfig=config;
export const passportDefaults={parking:'unknown',chargingReady:'unknown',longTrip:300,winterMargin:30,primaryStation:'',primarySource:'',backupStation:'',backupSource:'',chargeChecked:'',chargeRate:.25,chargePower:7.4,chargeSessions:2,detourMinutes:0,chargingNotes:'',trialPriorities:[]};
export const priorities=['Autoroute','Stationnement','Coffre','Sièges enfants','Accessibilité','Recharge','Confort'];
export const outcomeLabels={pursue:'Je souhaite poursuivre',compare:'Je compare encore',pause:'Je mets mon projet en pause',purchased:'J’ai acheté ce véhicule'};
export const reasonLabels={none:'Aucun frein particulier',budget:'Budget',charging:'Recharge',range:'Autonomie',comfort:'Confort / usage',availability:'Disponibilité',timing:'Calendrier',other:'Autre'};
export const sameProject=(a,b)=>!!a&&!!b&&Object.keys({...a,...b}).every(k=>JSON.stringify(a[k])===JSON.stringify(b[k]));
export function distanceKm(a,b){const r=x=>x*Math.PI/180,dlat=r(b.lat-a.lat),dlon=r(b.lon-a.lon);return 6371*2*Math.asin(Math.min(1,Math.sqrt(Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlon/2)**2)));}
export function assessPassport(buyer,vehicle){const p={...passportDefaults,...buyer};const winter=vehicle.autonomy*(1-p.winterMargin/100),usable=winter*.8;const weekly=p.km/52*vehicle.conso/100*1.1,sessionEnergy=weekly/p.chargeSessions;const concerns=[];if(p.chargingReady!=='confirmed')concerns.push('Votre solution principale de recharge reste à confirmer.');if(p.charging==='public'&&(!p.primaryStation||!p.backupStation||p.primaryStation===p.backupStation))concerns.push('Identifiez deux stations distinctes, dont une solution de secours.');if(p.charging==='public'&&!p.chargeChecked)concerns.push('Vérifiez les tarifs, les accès et la compatibilité sur place ou auprès de l’opérateur.');if(p.daily>usable)concerns.push('Votre trajet quotidien dépasse la plage d’autonomie prudente de ce scénario.');if(p.longTrip>usable)concerns.push('Votre long trajet nécessite de préparer une ou plusieurs pauses recharge.');if(vehicle.priceMin>p.budget)concerns.push('Le prix indicatif de ce modèle dépasse votre budget.');if(p.charging==='public'&&p.chargeChecked&&(Date.now()-new Date(p.chargeChecked).getTime())/86400000>30)concerns.push('Votre dernière vérification de recharge a plus de 30 jours : actualisez-la.');return {winter,usable,weekly,sessionEnergy,hours:sessionEnergy/p.chargePower,monthlyEnergy:weekly*52/12*p.chargeRate,weeklyDetour:p.detourMinutes*p.chargeSessions,concerns,title:p.chargingReady==='unavailable'?'Sécurisez la recharge avant de choisir.':concerns.length?'Un projet à préciser avant de vous engager.':'Les éléments déclarés permettent de préparer un essai.'};}
