import React from 'react';
import {publicPages,publicPaths} from './public-content';
import {trackEvent,openConsent} from './measurement';
import './dashboard.css';
import Consent from './Consent';
export function PublicArticle({path}){const p=publicPages[path];if(!p)return null;return <main className="container public-article"><nav aria-label="Fil d’Ariane" className="public-breadcrumb"><a href="/">VOLTÉO</a><span aria-hidden="true"> / </span><span>{p.eyebrow}</span></nav><div className="eyebrow">{p.eyebrow}</div><h1>{p.heading}</h1><p className="intro">{p.intro}</p><div className="actions"><a className="button" href={p.href} onClick={()=>trackEvent('landing_cta',{campaign:p.campaign})}>{p.cta} →</a><a className="button secondary" href="/catalogue">Explorer les modèles</a></div><p className="muted">VOLTÉO vous aide à comparer. Les estimations dépendent de vos hypothèses et les données du catalogue restent à confirmer.</p><div className="public-sections">{p.sections.map((s,i)=><section className="panel" key={s.heading}><span className="eyebrow">0{i+1}</span><h2>{s.heading}</h2><p>{s.text}</p></section>)}</div><section className="panel public-faq"><h2>Vos questions, simplement.</h2>{p.faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section><section className="panel"><h2>Continuez à préparer votre projet.</h2><div className="public-related">{publicPaths.filter(x=>x!==path).map(x=><a href={x} key={x}>{publicPages[x].title} →</a>)}<a href="/sources">Sources et limites des données →</a></div></section><a className="button" href={p.href} onClick={()=>trackEvent('landing_cta',{campaign:p.campaign})}>{p.cta} →</a></main>;}
export function PublicSite({path}){return <div className="public-shell"><header><a className="brand" href="/">VOLTÉO</a><nav aria-label="Navigation principale"><a href="/catalogue">Véhicules</a><a href="/simulateur">Mon budget</a><a href="/connexion">Mon compte</a></nav></header><div className="public-scroll" tabIndex={0} aria-label="Contenu de la page" role="region"><PublicArticle path={path}/><footer><a href="/mentions-legales">Mentions légales</a><a href="/confidentialite">Confidentialité</a><button className="text-button" onClick={openConsent}>Confidentialité et cookies</button></footer></div></div>;}

export function PublicRoot({path}){return <><PublicSite path={path}/><Consent/></>;}
