export const publicPages={
 '/economies-voiture-electrique':{
  title:'Passer à l’électrique : budget, usage et projet automobile',description:'Curieux de l’électrique ? Comparez énergie et coût total selon votre quotidien, explorez les modèles et préparez un échange avec une concession.',eyebrow:'VOTRE BUDGET AUTOMOBILE',heading:'L’électrique, qu’est-ce que cela changerait pour vous ?',intro:'Vous n’avez pas besoin d’avoir déjà décidé de changer. Partez de vos trajets, vérifiez vos possibilités de recharge et comparez les coûts. VOLTÉO vous aide à construire votre projet avant de contacter une concession.',cta:'Explorer mon budget',href:'/simulateur',campaign:'budget',
  sections:[
   {heading:'Commencez par vos kilomètres, pas par une promesse.',text:'Notez votre kilométrage annuel, la consommation réelle de votre voiture et le prix du carburant que vous payez. Pour comparer l’énergie sur 100 km, multipliez les litres consommés par le prix du litre. Pour l’électrique, multipliez les kWh consommés par votre tarif de recharge et tenez compte des pertes.'},
   {heading:'Domicile, travail ou bornes : le tarif change le calcul.',text:'Une moyenne nationale ne raconte pas votre quotidien. Répartissez vos recharges entre domicile et bornes publiques, avec les prix de vos contrats. Ajoutez les abonnements ou frais applicables. Le simulateur VOLTÉO permet de modifier ces hypothèses ; ses valeurs initiales ne sont pas un devis.'},
   {heading:'Le coût total va au-delà de la pompe.',text:'Pour décider de conserver votre thermique ou d’acheter un électrique, comparez la décote sur votre durée de détention, l’énergie, l’entretien, l’assurance, l’installation de recharge et les intérêts éventuels. La mensualité du crédit n’est pas le coût total du véhicule : évitez de compter deux fois le capital financé.'},
   {heading:'Du calcul au projet avec une concession.',text:'Le budget n’est qu’une partie de votre choix : autonomie, recharge et confort comptent aussi. Après avoir exploré les modèles adaptés, préparez vos questions sur le prix réel, la reprise et le financement. Consultez les offres locales pour choisir un professionnel ; une demande ou un partage de dossier nécessite votre action.'},
   {heading:'Trois informations pour avancer.',text:'Préparez votre kilométrage annuel, votre facture ou contrat d’énergie et la valeur estimée de revente de votre voiture. Choisissez un modèle à comparer, puis testez un scénario prudent et un scénario correspondant à votre usage. Une estimation peut faire apparaître une économie comme un surcoût.'}
  ],faq:[['Puis-je explorer sans être prêt à acheter ?','Oui. Le diagnostic et le budget vous permettent de préciser votre projet à votre rythme. Aucun contact n’est envoyé depuis la simulation. Vous décidez ensuite si vous souhaitez demander un essai auprès d’un professionnel.'],['Pourquoi économiser sur la recharge ne garantit-il pas un gain total ?','Le bilan inclut aussi la décote, l’entretien, l’assurance, l’installation et les intérêts éventuels. Garder un thermique déjà possédé et acheter un électrique sont deux scénarios différents. Comparez-les sur la même durée.'],['L’électrique coûte-t-il toujours moins cher ?','Non. Le résultat dépend du prix d’achat, de la revente, du kilométrage, des tarifs de recharge et des autres dépenses. Comparez le coût total sur une même durée.'],['Les chiffres de VOLTÉO constituent-ils une offre ?','Non. Le catalogue comporte des exemples de démonstration. Confirmez les prix et caractéristiques auprès du constructeur ou du professionnel avant de vous engager.'],['Puis-je comparer en rechargeant uniquement sur bornes publiques ?','Oui. Dans le simulateur, choisissez une part de recharge à domicile de 0 % et renseignez le tarif public correspondant à vos habitudes.']]
 },
 '/recharge-voiture-electrique':{
  title:'Recharge électrique : préparer son quotidien et son budget',description:'Domicile, copropriété, travail ou bornes publiques : préparez un scénario de recharge compatible avec vos trajets avant de choisir votre électrique.',eyebrow:'UNE RECHARGE QUI VOUS CORRESPOND',heading:'L’électrique commence par une question : où recharger ?',intro:'Votre voiture passe une partie de sa journée à l’arrêt. Repérez quand et où une recharge serait possible, puis vérifiez les conditions avant de choisir votre modèle.',cta:'Préparer ma recharge',href:'/recharge',campaign:'recharge',
  sections:[
   {heading:'À domicile : vérifier avant de prévoir.',text:'Identifiez votre place de stationnement, la puissance disponible et le trajet du câblage. Un professionnel qualifié doit vérifier l’installation et le matériel adapté. Le montant de l’installation dépend du logement et des travaux : demandez un devis.'},
   {heading:'En copropriété ou au travail : clarifier les accès.',text:'Renseignez-vous sur les démarches, les autorisations, les horaires et la facturation. Un point de recharge présent sur un parking ne garantit pas qu’il vous sera accessible. Retenez uniquement les solutions dont vous avez confirmé les conditions.'},
   {heading:'Sur la route : prévoir le temps et le tarif.',text:'Consultez les connecteurs, la puissance, les conditions tarifaires et la disponibilité lorsqu’une source récente existe. La puissance maximale annoncée ne reste pas constante pendant toute une recharge ; la voiture, la température et le niveau de batterie influencent la durée.'},
   {heading:'Construire votre scénario.',text:'Partez de vos kilomètres quotidiens, de la consommation estimée et de votre temps de stationnement. Préparez une solution habituelle et une solution de secours. VOLTÉO vous aide à estimer un besoin quotidien ; confirmez les valeurs en situation réelle.'}
  ],faq:[['Une borne affichée sur une carte est-elle disponible ?','Pas nécessairement. La présence d’un point et sa disponibilité sont deux informations différentes. Vérifiez la fraîcheur de la source et les conditions d’accès.'],['Puis-je rouler en électrique sans recharge à domicile ?','C’est à étudier selon les bornes accessibles, votre budget et vos trajets. Comparez le temps consacré à la recharge et son coût avant de décider.']]
 },
 '/essai-electrique-les-ulis':{
  title:'Préparer un essai de voiture électrique autour des Ulis',description:'Préparez vos critères, votre parcours d’essai et vos questions recharge autour des Ulis. Découvrez le pilote VOLTÉO et les offres partenaires disponibles.',eyebrow:'LE PILOTE VOLTÉO · LES ULIS',heading:'Le bon essai commence avant de prendre le volant.',intro:'Budget, autonomie, recharge, confort : définissez ce que vous voulez vérifier. Le pilote VOLTÉO vous aide à préparer une rencontre utile avec un professionnel autour des Ulis.',cta:'Consulter les offres locales',href:'/offres-locales',campaign:'essai_ulis',
  sections:[
   {heading:'Choisissez trois points à vérifier.',text:'Reprenez un trajet représentatif de votre semaine. Évaluez la position de conduite, l’espace utile, les commandes et les possibilités de recharge qui vous concernent. Gardez vos priorités dans votre passeport pour comparer les véhicules après les essais.'},
   {heading:'Vérifiez l’offre et la version exacte.',text:'Une photo ou un nom de modèle ne décrit pas toute une offre. Confirmez finition, batterie, année, état, kilométrage, prix total avec frais et délai. Les offres du pilote distinguent leur statut et leur fraîcheur ; leur disponibilité doit être confirmée par le partenaire.'},
   {heading:'Une demande n’est pas une réservation confirmée.',text:'Consultez les offres locales puis transmettez une demande au professionnel choisi. Le créneau dépend de sa confirmation. Le rayon du pilote est affiché dans VOLTÉO et peut évoluer ; la présence d’une concession dans un catalogue ne prouve pas à elle seule un partenariat actif.'},
   {heading:'Après l’essai, notez vos impressions.',text:'Revenez sur vos priorités et sur les points qui restent à vérifier. Conservez un bilan utile à votre décision. Votre compte permet de suivre les échanges et de choisir les informations que vous partagez avec le professionnel.'}
  ],faq:[['Le pilote garantit-il un rendez-vous ?','Non. Le professionnel confirme le créneau et la disponibilité du véhicule. Une demande envoyée ne vaut ni réservation confirmée ni commande.'],['Mes informations sont-elles transmises à toutes les concessions ?','La demande est adressée à la concession sélectionnée avec votre autorisation. Le partage du dossier acheteur relève d’un choix distinct.']]
 }
};
export const publicPaths=Object.keys(publicPages);
