import React,{useEffect,useRef,useState} from 'react';
import {Link,NavLink,useLocation} from 'react-router-dom';
import {Icon} from './Experience';
import LocationBar from './LocationBar';
import './workspace.css';
const explore=[['/','Vue d’ensemble','home'],['/catalogue','Véhicules','car'],['/comparateur','Comparateur','compare'],['/offres-locales','Offres locales','offers']];
const project=[['/projet','Mon projet','passport'],['/passeport','Mon passeport','passport'],['/simulateur','Mon budget','wallet'],['/recharge','Ma recharge','bolt']];
const local=[['/autour-de-moi','Autour de moi','map'],['/guides','Guides pratiques','book'],['/diagnostic','Diagnostic','bolt']];
export default function Workspace({app:a,theme,setTheme,children}){
 const loc=useLocation(),dialog=useRef(null),[open,setOpen]=useState(false),[compact,setCompact]=useState(()=>{try{return localStorage.getItem('volteo-sidebar')==='compact';}catch{return false;}});
 const pro=a.isPro,manage=['dealer','admin'].includes(a.user?.role);
 const groups=pro?[
  ['MON ACTIVITÉ',[['/','Vue d’ensemble','home'],['/professionnel','Demandes et essais','passport'],...(manage?[['/stock','Mes offres','offers']]:[]),['/compte','Mon établissement','user']]],
  ['OUTILS',explore.slice(1).concat([['/simulateur','Calcul de budget','wallet'],['/autour-de-moi','Carte locale','map']])]
 ]:[['DÉCOUVRIR',explore],['MON PROJET',project],['À PROXIMITÉ',local]];
 if(a.user?.role==='admin')groups.push(['GESTION',[['/admin','Administration','shield']]]);
 const [section,setSection]=useState('');
 const sectionName=section||groups[0][0];
 const current=groups.flatMap(x=>x[1]).find(x=>x[0]===loc.pathname)?.[1]||(loc.pathname.startsWith('/vehicules/')?'Fiche véhicule':'Votre espace');
 const nextActions={ '/diagnostic':['Construire mon projet','/projet'], '/projet':['Voir mon passeport','/passeport'], '/passeport':['Explorer les modèles','/catalogue'], '/catalogue':['Comparer ma sélection','/comparateur'], '/comparateur':['Calculer mon budget','/simulateur'], '/simulateur':['Préparer mon essai','/offres-locales'], '/offres-locales':['Voir la carte locale','/autour-de-moi'], '/autour-de-moi':['Consulter les offres','/offres-locales'], '/recharge':['Vérifier mon projet','/diagnostic'], '/partenaires':['Créer mon compte pro','/connexion?inscription=1&type=pro'], '/professionnel':['Voir mes offres','/stock'] };
 const next=nextActions[loc.pathname];
 useEffect(()=>{setOpen(false);},[loc.pathname,loc.search]);
 useEffect(()=>{const el=dialog.current;if(open&&!el.open)el.showModal();else if(!open&&el.open)el.close();},[open]);
 useEffect(()=>{try{localStorage.setItem('volteo-sidebar',compact?'compact':'expanded');}catch{}},[compact]);
 const links=()=> <><Link className="workspace-brand" to="/" onClick={()=>setOpen(false)} aria-label="VOLTÉO — Accueil"><Icon name="bolt" size={28}/><span>VOLTÉO<small>{pro?'PARTENAIRES':'VOTRE ESPACE ÉLECTRIQUE'}</small></span></Link><label className="workspace-section-picker">Rubrique<select value={sectionName} onChange={e=>setSection(e.target.value)}>{groups.map(([title])=><option key={title}>{title}</option>)}</select></label><nav className="workspace-nav" aria-label="Navigation latérale">{groups.map(([title,items])=><section key={title} className={sectionName===title?'is-current-group':''}><h2>{title}</h2>{items.map(([to,label,icon])=><NavLink end to={to} key={to} title={label} aria-label={label} onClick={()=>setOpen(false)} className={({isActive})=>'workspace-link'+(isActive||(to==='/catalogue'&&loc.pathname.startsWith('/vehicules/'))?' selected':'')}><Icon name={icon}/><span>{label}</span>{to==='/comparateur'&&a.compare.length>0&&<b>{a.compare.length}</b>}</NavLink>)}</section>)}</nav><div className="workspace-side-bottom"><Link to="/pilote" title="Pilote Les Ulis" onClick={()=>setOpen(false)}><span className="status-dot"/><span>Pilote · Les Ulis<small>{a.pilot?.radius||20} km autour de vous</small></span></Link><Link to="/sources" title="Sources et fraîcheur" onClick={()=>setOpen(false)}><Icon name="shield"/><span>Sources et fraîcheur</span></Link>{!pro&&<Link to="/partenaires" title="Espace professionnels" onClick={()=>setOpen(false)}><Icon name="user"/><span>Espace professionnels ↗</span></Link>}</div></>;
 return <div className={'workspace'+(compact?' is-compact':'')}><aside className="workspace-sidebar">{links()}<button className="workspace-collapse" onClick={()=>setCompact(!compact)} aria-label={compact?'Déployer la navigation':'Réduire la navigation'} aria-expanded={!compact}><Icon name={compact?'arrow':'back'}/><span>Réduire le menu</span></button></aside><div className="workspace-main"><header className="workspace-toolbar"><div className="workspace-heading"><button className="workspace-mobile-toggle secondary" aria-label="Ouvrir la navigation" aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(true)}><Icon name="menu"/></button><div><small>{pro?'VOLTÉO / PROFESSIONNEL':'VOLTÉO / ACHETEUR'}</small><strong>{current}</strong></div></div><div className="workspace-actions">{next&&<Link className="workspace-next-action" to={next[1]}>{next[0]} <span>→</span></Link>}<span className="workspace-demo">Prototype · données à vérifier</span><button className="secondary" aria-label={theme==='dark'?'Activer le thème clair':'Activer le thème sombre'} onClick={()=>setTheme(theme==='dark'?'light':'dark')}><Icon name={theme==='dark'?'sun':'moon'}/></button><Link className="workspace-account" to={a.user?'/compte':'/connexion'}><Icon name="user"/><span>{a.user?.name?.split(' ')[0]||'Connexion'}</span></Link></div></header><LocationBar app={a}/>{children}</div><dialog ref={dialog} className="workspace-drawer" aria-label="Navigation VOLTÉO" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)}><button className="workspace-drawer-close secondary" aria-label="Fermer la navigation" onClick={()=>setOpen(false)}><Icon name="close"/></button>{links()}</dialog></div>;
}
