import React,{useEffect,useRef,useState} from 'react';
import {Link,NavLink,useLocation,useNavigate} from 'react-router-dom';
import {Icon} from './Experience';
import LocationBar from './LocationBar';
import './workspace.css';
import './professional.css';
import {api,setCsrf} from './api';
const explore=[['/','Vue d’ensemble','home'],['/catalogue','Véhicules','car'],['/comparateur','Comparateur','compare'],['/offres-locales','Offres locales','offers']];
const project=[['/projet','Mon projet','passport'],['/passeport','Mon passeport','passport'],['/simulateur','Mon budget','wallet'],['/recharge','Ma recharge','bolt']];
const local=[['/autour-de-moi','Autour de moi','map'],['/guides','Guides pratiques','book'],['/diagnostic','Diagnostic','bolt']];
export default function Workspace({app:a,theme,setTheme,children}){
 const loc=useLocation(),dialog=useRef(null),[open,setOpen]=useState(false),[compact,setCompact]=useState(()=>{try{return localStorage.getItem('volteo-sidebar')==='compact';}catch{return false;}});
 const nav=useNavigate(),[loggingOut,setLoggingOut]=useState(false);
 async function logout(){
  if(loggingOut)return;
  setLoggingOut(true);
  try{await api('/logout','POST',{});setCsrf(null);a.resetJourney();setOpen(false);nav('/',{replace:true});await a.refresh();}
  catch(error){a.setToast(error.message||'Impossible de vous déconnecter. Réessayez.');}
  finally{setLoggingOut(false);}
 }
 const pro=a.professionalView?.enabled?a.professionalView.mode==='pro':a.isPro,manage=['dealer','admin'].includes(a.user?.role);
 const groups=pro?[
  ['PILOTER',[[a.user?.role==='admin'?'/admin':manage?'/tableau-de-bord':'/compte',manage?'Accueil professionnel':'Activation du compte','home'],...(manage?[['/professionnel','Demandes clients','user'],['/tableau-de-bord?vue=leads','Agenda et relances','passport'],['/stock','Stock et offres','offers'],['/tableau-de-bord?vue=performance','Performance','wallet']]:[])]],
  ['ÉTABLISSEMENT',[['/compte','Mon établissement','user'],['/parametres','Mon compte et sécurité','shield']]]
 ]:[['DÉCOUVRIR',explore],['MON PROJET',project],['À PROXIMITÉ',local]];
 if(pro&&a.user?.role==='admin')groups.push(['GESTION',[['/admin/gestion','Comptes et partenaires','shield']]]);
 const [section,setSection]=useState('');
 const sectionName=groups.some(g=>g[0]===section)?section:groups[0][0];
 const current=groups.flatMap(x=>x[1]).find(x=>x[0]===loc.pathname+loc.search)?.[1]||groups.flatMap(x=>x[1]).find(x=>x[0]===loc.pathname)?.[1]||(loc.pathname.startsWith('/vehicules/')?'Fiche véhicule':'Votre espace');
 const nextActions={ '/diagnostic':['Construire mon projet','/projet'], '/projet':['Voir mon passeport','/passeport'], '/passeport':['Explorer les modèles','/catalogue'], '/catalogue':['Comparer ma sélection','/comparateur'], '/comparateur':['Calculer mon budget','/simulateur'], '/simulateur':['Préparer mon essai','/offres-locales'], '/offres-locales':['Voir la carte locale','/autour-de-moi'], '/autour-de-moi':['Consulter les offres','/offres-locales'], '/recharge':['Vérifier mon projet','/diagnostic'], '/partenaires':['Créer mon compte pro','/connexion?inscription=1&type=pro'], '/professionnel':['Voir mes offres','/stock'] };
 const next=pro?null:nextActions[loc.pathname];
 useEffect(()=>{setOpen(false);},[loc.pathname,loc.search]);
 useEffect(()=>{const el=dialog.current;if(open&&!el.open)el.showModal();else if(!open&&el.open)el.close();},[open]);
 useEffect(()=>{try{localStorage.setItem('volteo-sidebar',compact?'compact':'expanded');}catch{}},[compact]);
 const links=()=> <><Link className="workspace-brand" to={pro?(a.user?.role==='admin'?'/admin':manage?'/tableau-de-bord':'/compte'):'/'} onClick={()=>setOpen(false)} aria-label="VOLTÉO — Accueil" ><Icon name="bolt" size={28}/><span>VOLTÉO<small>{pro?'PRO · ESPACE DE TRAVAIL':'VOTRE ESPACE ÉLECTRIQUE'}</small></span></Link><label className="workspace-section-picker">Rubrique<select value={sectionName} onChange={e=>setSection(e.target.value)}>{groups.map(([title])=><option key={title}>{title}</option>)}</select></label><nav className="workspace-nav" aria-label="Navigation latérale">{groups.map(([title,items])=><section key={title} className={sectionName===title?'is-current-group':''}><h2>{title}</h2>{items.map(([to,label,icon])=><NavLink end to={to} key={to} title={label} aria-label={label} onClick={()=>setOpen(false)} className={({isActive})=>'workspace-link'+((isActive&&to===loc.pathname+loc.search)||(to==='/catalogue'&&loc.pathname.startsWith('/vehicules/'))?' selected':'')}><Icon name={icon}/><span>{label}</span>{to==='/comparateur'&&a.compare.length>0&&<b>{a.compare.length}</b>}</NavLink>)}</section>)}</nav><div className="workspace-side-bottom">{pro&&<div className="pro-establishment"><span className="eyebrow">ÉTABLISSEMENT</span><strong>{a.user?.company||a.user?.name||'Votre concession'}</strong><small>{manage?'Accès professionnel actif':'Validation en attente'}</small></div>}{!pro&&<Link to="/pilote" title="Pilote Les Ulis" onClick={()=>setOpen(false)}><span className="status-dot"/><span>Pilote · Les Ulis<small>{a.pilot?.radius||20} km autour de vous</small></span></Link>}<Link to="/sources" title="Sources et fraîcheur" onClick={()=>setOpen(false)}><Icon name="shield"/><span>Sources et fraîcheur</span></Link>{!pro&&<Link to="/partenaires" title="Espace professionnels" onClick={()=>setOpen(false)}><Icon name="user"/><span>Espace professionnels ↗</span></Link>}</div></>;
 return <div className={'workspace'+(pro?' professional-workspace':'')+(compact?' is-compact':'')}><aside className="workspace-sidebar">{links()}<button className="workspace-collapse" onClick={()=>setCompact(!compact)} aria-label={compact?'Déployer la navigation':'Réduire la navigation'} aria-expanded={!compact}><Icon name={compact?'arrow':'back'}/><span>Réduire le menu</span></button></aside><div className="workspace-main"><header className="workspace-toolbar"><div className="workspace-heading"><button className="workspace-mobile-toggle secondary" aria-label="Ouvrir la navigation" aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(true)}><Icon name="menu"/></button><div><small>{pro?'VOLTÉO / PROFESSIONNEL':'VOLTÉO / ACHETEUR'}</small><strong>{current}</strong></div></div><div className="workspace-actions">{a.professionalView?.enabled&&<button className="secondary view-switch" onClick={a.professionalView.switchView}><Icon name={pro?'car':'offers'}/><span>{pro?'Vue acheteur':'Retour espace pro'}</span><span aria-hidden="true">⇄</span></button>}{next&&<Link className="workspace-next-action" to={next[1]}>{next[0]} <span>→</span></Link>}<span className="workspace-demo">Prototype · données à vérifier</span><button className="secondary" aria-label={theme==='dark'?'Activer le thème clair':'Activer le thème sombre'} onClick={()=>setTheme(theme==='dark'?'light':'dark')}><Icon name={theme==='dark'?'sun':'moon'}/></button><Link className="workspace-account" to={a.user?'/compte':'/connexion'}><Icon name="user"/><span>{a.user?.name?.split(' ')[0]||'Connexion'}</span></Link>{a.user&&<button type="button" className="secondary workspace-logout" onClick={logout} disabled={loggingOut} aria-busy={loggingOut} aria-label={loggingOut?'Déconnexion en cours':'Se déconnecter'} title="Se déconnecter"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M9 21H4V3h5m5 5 4 4-4 4m-6-4h13"/></svg><span>{loggingOut?'Déconnexion…':'Se déconnecter'}</span></button>}</div></header>{a.professionalView?.buyerPreview&&<div className="buyer-preview-bar"><b>Vue acheteur · démonstration</b><span>Votre compte pro reste connecté. Aucun envoi de demande ni enregistrement dans un compte acheteur.</span></div>}{!pro&&<LocationBar app={a}/>} {children}</div><dialog ref={dialog} className="workspace-drawer" aria-label="Navigation VOLTÉO" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)}><button className="workspace-drawer-close secondary" aria-label="Fermer la navigation" onClick={()=>setOpen(false)}><Icon name="close"/></button>{links()}</dialog></div>;
}
